### ISSUE TITLE
NoSuchMethodError in "m.homeserver" on Login

### ISSUE THREAD

**Issue by MurzNN** [sputnik-messenger/sputnik-messenger-tickets#39]
I try to login after first install of app, but got this error at some time after pressing Login:
![image](https://user-images.githubusercontent.com/336662/62138740-d2338e00-b2f0-11e9-9c6f-506b6ccae997.png)
Other apps (Riot-Android, RiotX, Pattle) connects normally.
I have use my homeserver, not matrix.org, maybe here is problem?

With my second matrix.org account Sputnik connects successfully.

Did you need more info for debug this issue?

**Comment by forgemo** [comment]
Thanks for reporting :) 

I created a test account on your server called 'sputnik-test' and was able to reproduce your issue.

There is an optional field in the LoginResponse sent from server to client called `well_known`. Your server doesn't set this optional field, which is perfectly fine. 

The bug is caused by Sputnik expecting it to be set. .... I'm going to fix it. :+1:
